#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

# See comments in install script
app=$YNH_APP_INSTANCE_NAME
db_name=$app

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
admin=$(ynh_app_setting_get "$app" admin)
language=$(ynh_app_setting_get "$app" language)
final_path=$(ynh_app_setting_get "$app" final_path)
path_url="/"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

# If db_name doesn't exist, create it
if [ -z "$db_name" ]; then
	db_name=$(ynh_sanitize_dbid "$app")
	ynh_app_setting_set "$app" db_name "$db_name"
fi

# If final_path doesn't exist, create it
if [ -z "$final_path" ]; then
	final_path=/var/www/$app
	ynh_app_setting_set "$app" final_path "$final_path"
fi

# Check if admin is not null
if [[ "$admin" = "" || "$language" = "" ]]; then
    echo "Unable to upgrade, please contact support"
    ynh_die
fi

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# CHECK THE PATH
#=================================================

# Normalize the URL path syntax
#path_url=$(ynh_normalize_url_path $path_url)

#=================================================
# INSTALL DEPENDENCIES
#=================================================

# upgrade Node.js v4 to v6
# TODO: use https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_install_nodejs/ynh_install_nodejs
node_version=$(nodejs --version)
if [[ $node_version =~ ^v4.*$  ]]; then
	pushd /opt
	curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
	sudo apt-get -y install nodejs
fi

# add additional package for upgrade
ynh_package_install pkg-config libprotobuf-dev protobuf-compiler libicu-dev libidn11-dev postgresql-server-dev-all

#=================================================
# STANDARD UPGRADE STEPS
#=================================================

# Stop Mastodon Services
# Restart Mastodon
yunohost service stop "$app-web"
yunohost service stop "$app-sidekiq"
yunohost service stop "$app-streaming"

# Change owner of live folder
chown -R $app: $final_path/live

# Download Mastodon
ynh_setup_source "$final_path/live"                      "app-mastodon"

#=================================================
# NGINX CONFIGURATION
#=================================================

# TODO: use official helper ynh_add_nginx_config
# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@__PATH__@$app@g" ../conf/nginx.conf*
sed -i "s@__FINALPATH__@$final_path@g" ../conf/nginx.conf*
cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Upgrade rbenv and ruby plugins
ynh_setup_source "$final_path/.rbenv"                    "app-rbenv"
ynh_setup_source "$final_path/.rbenv/plugins/ruby-build" "app-ruby-build"

# Install ruby 2.5.1
(
	exec_as "$app" $final_path/.rbenv/bin/rbenv install 2.5.1 || true
	exec_as "$app" $final_path/.rbenv/bin/rbenv global 2.5.1 || true
	exec_as "$app" $final_path/.rbenv/versions/2.5.1/bin/ruby -v
)

# Create symlink for ruby
rm /usr/bin/ruby || true
ln -s $final_path/.rbenv/versions/2.5.1/bin/ruby /usr/bin/ruby || true

# Preconfig CSS & JS
# Install Mastodon
(
sudo su - $app <<MCOMMANDS
pushd ~/live
$final_path/.rbenv/versions/2.5.1/bin/gem install bundler
if [ "$(lsb_release --codename --short)" == "jessie" ]; then
	$final_path/.rbenv/versions/2.5.1/bin/bundle install --deployment --without development test
else
	$final_path/.rbenv/versions/2.5.1/bin/bundle install --deployment --force --without development test
fi
yarn install --pure-lockfile
MCOMMANDS
)

# Apply Mastodon upgrade
(
pushd $final_path/live
RAILS_ENV=production $final_path/.rbenv/versions/2.5.1/bin/bundle exec rails assets:clean
RAILS_ENV=production $final_path/.rbenv/versions/2.5.1/bin/bundle exec rails assets:precompile
popd

sudo su - $app <<COMMANDS
pushd ~/live
RAILS_ENV=production $final_path/.rbenv/versions/2.5.1/bin/bundle exec rails db:migrate
# Upgrade to 2.2.0
RAILS_ENV=production $final_path/.rbenv/versions/2.5.1/bin/bundle exec rails mastodon:maintenance:remove_regeneration_markers
COMMANDS
)
#=================================================
# RESTART MASTODON
#=================================================

yunohost service start "$app-web"
yunohost service start "$app-sidekiq"
yunohost service start "$app-streaming"

# Waiting start all services
sleep 30

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx

#=================================================
# SETUP SSOWAT
#=================================================

ynh_app_setting_set "$app" unprotected_uris "/"

#=================================================
# RELOAD ssowatconf
#=================================================

sudo yunohost app ssowatconf
